name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  app: # select this
    required: true
    description: 'select app cmd'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
